transfers/urls.py
from django.urls import path
from . import views

app_name = 'transfers'
urlpatterns = [
    path('', views.index, name='index'),
    
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include
from . import views
app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
path('register/', views.register, name='register'),
]

virtual_money/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('transfers.urls')),


    
]

users/models.py
from datetime import date
import email
from django.utils.translation import gettext_lazy as _
from email.policy import default
from django.utils import timezone
from django.db import models
from django_countries.fields import CountryField
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255,unique=True, error_messages={
        'unique':("A user with that email already exist.")})
    phone_number = models.CharField(max_length=20)
    date_of_birth = models.DateField()
    nationality = CountryField(blank_label='(select country)')
    is_active = models.BooleanField(('Active'),default=True)
    username = models.CharField(unique=True, max_length=50)
    date_joined = models.DateTimeField(('date joined'),default=timezone.now)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELD = ['first_name','last_name','phone_number','email','date_of_birth','username']

    

users/forms.py
from dataclasses import fields
from django import forms
from . models import User
from django.core.exceptions import ValidationError


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name','last_name','phone_number','email','date_of_birth','nationality','username')
        # widgets = {'date_of_birth': DatePickerInput(),}

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

transfers/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html' )

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from . forms import UserRegistrationForm
from django.http import HttpResponseRedirect
from django.urls import reverse
def register(request):

    if request.method != 'POST':
        form = UserRegistrationForm()
        
    else:
        form = UserRegistrationForm(data=request.POST)
        print(form)
        if form.is_valid():
            print(form)
            new_user = form.save()
            login(request,new_user)
            return HttpResponseRedirect(reverse('users:login'))
    context = {'form':form}
    return render(request , 'registration/register.html', context)

templates/base.html
{% load bootstrap4 %}


<!doctype html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>Quicky Transfer Money</title>
    {% bootstrap_css %}
    
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <div class="collapse navbar-collapse" id="navbarCollapse">   
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                            <span class="navbar-text">Welcome {{ user.username }}.</span>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Log
                            out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                            </li>
                            <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log
                            in</a></li>
                        {% endif %}
                    </ul>
            </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
        </div>
        <div>
        {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block page_header %}
<div class="jumbotron">

    <h1 class="display-3">Send money to your loved ones.</h1>
    <p class="lead">You can easily send money across the globe with 
        the most secure and quick platform.
        </p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
role="button">Register &raquo;</a>
</div>

{% endblock page_header %}